@startmindmap
* Sistema de Gestão de Estágios
** Para quê serve?
*** Organizar o processo
*** Reduzir burocracia
*** Centralizar informações

** O que é?
*** Sistema acadêmico
*** Plataforma de gestão

** Como fazer?
*** Cadastro de alunos
*** Cadastro de empresas
*** Cadastro de vagas
*** Candidaturas

** O que contém?
*** Dados dos alunos
*** Vagas
*** Documentos
*** Relatórios
@endmindmap