# Generated by Django 6.0.5 on 2026-05-29 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_aluno_coordenador_documento_empresa_estagio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=20)),
                ('data_candidatura', models.DateField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.aluno')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vaga')),
            ],
            options={
                'unique_together': {('aluno', 'vaga')},
            },
        ),
    ]
