@startsalt
{
{^"Upload de Documentos"

Solicitação: #2026-01

--------------------------------

Termo de Compromisso     | [ Upload ]
Plano de Atividades      | [ Upload ]
Comprovante Matrícula    | [ Upload ]

--------------------------------

Arquivo selecionado:
"documento.pdf"

--------------------------------

[ Enviar ] [ Voltar ]

}
}
@endsalt