@startsalt
{
{+Vagas de Estágio

Buscar: | "            "

--------------------------------

Estágio em TI  
Empresa: XPTO  
[ Ver detalhes ] [ Candidatar ]

--

Estágio em Administração  
Empresa: ABC  
[ Ver detalhes ] [ Candidatar ]

}
}
@endsalt